// src/ressources/products.js
const products = [
  {
    id: 1,
    name: "Bague MK",
    description: " excellent choix pour vos souvenir.",
    price: 99.99,
    image: "/image/bague.PNG",
    category: "bijoux",
  },
  {
    id: 2,
    name: "sac a main",
    description: " qualité premium et durable.",
    price: 29.99,
    image: "/image/sac.PNG",
    category: "sac",
  },
  {
    id: 3,
    name: "Casque JBL",
    description: " notre coup de cœur client.",
    price: 39.99,
    image: "/image/casque.PNG",
    category: "électronique",
    },
   {
    id: 4,
    name: "Montre connectée",
    price: 149.99,
    description: "Montre élégante avec suivi d’activité et notifications.",
    image: "/image/montre.PNG",
    category: "électronique",
  },
  {
    id: 5,
    name: "Casque Bluetooth",
    price: 89.99,
    description: "Casque sans fil à réduction de bruit, autonomie 30h.",
    image: "/image/casque_sony.PNG",
    category: "électronique",
  },
  {
    id: 6,
    name: "Sac à dos en cuir",
    price: 119.99,
    description: "Sac à dos spacieux en cuir véritable, parfait pour le quotidien.",
    image: "/image/sac_en_cuir.PNG",
    category: "sac",
  },
  {
    id: 7,
    name: "Lunettes de soleil",
    price: 49.99,
    description: "Lunettes de soleil UV400, design unisexe et monture légère.",
    image: "/image/lunette.PNG"
  },
  {
    id: 8,
    name: "Chaussures de sport",
    price: 59.99,
    description: "Chaussures respirantes et confortables pour le sport et la marche.",
    image: "/image/chaussure_sport.PNG",
    category: "chaussures",
  },
    {
    id: 8,
    name: "Chaussure élégante noire",
    description: "Chaussure en cuir noir idéale pour les occasions formelles.",
    price: 79.99,
    image: "/image/chaussure1.PNG",
    category: "chaussures",
  },
  {
    id: 9,
    name: "Chaussure brune classique",
    description: "Modèle confortable et résistant, parfait pour un usage quotidien.",
    price: 69.99,
    image: "/image/chaussure2.PNG",
    category: "chaussures",
  },
  {
    id: 10,
    name: "Chaussure de sport rose",
    description: "Design sportif et léger, excellent maintien du pied.",
    price: 59.99,
    image: "/image/chaussure3.PNG",
    category: "chaussures",
  },
  {
    id: 11,
    name: "Chaussure de course grise",
    description: "Chaussure respirante avec semelle antidérapante.",
    price: 64.99,
    image: "/image/chaussure4.PNG",
    category: "chaussures",
  },
  {
    id: 12,
    name: "Chaussure Adidas blanche",
    description: "Modèle intemporel et confortable pour le sport ou la marche.",
    price: 89.99,
    image: "/image/chaussure5.PNG",
    category: "chaussures",
  },
  {
    id: 13,
    name: "Chaussure décontractée beige",
    description: "Style urbain avec confort optimal pour vos journées actives.",
    price: 74.99,
    image: "/image/chaussure6.PNG",
    category: "chaussures",
  },
  {
    id: 14,
    name: "Chaussure running bleue",
    description: "Chaussure de sport dynamique avec amorti amélioré.",
    price: 84.99,
    image: "/image/chaussure8.PNG",
    category: "chaussures",
  },
  {
    id: 15,
    name: "Sac à main diamanté",
    description: "Sac chic et élégant, orné de détails brillants.",
    price: 129.99,
    image: "/image/sac_diamant.PNG",
    category: "sac",
  },
  {
    id: 16,
    name: "Sac à dos en cuir",
    description: "Sac robuste et stylé, idéal pour le travail ou les voyages.",
    price: 119.99,
    image: "/image/sac_en_cuir.PNG",
    category: "sac",
  },
  {
    id: 17,
    name: "Boucles d’oreilles dorées",
    description: "Bijoux raffinés pour compléter vos tenues élégantes.",
    price: 49.99,
    image: "/image/boucle1.PNG",
    category: "bijoux",
  },
  {
    id: 18,
    name: "Boucles d’oreilles circulaires",
    description: "Anneaux dorés intemporels, légers et élégants.",
    price: 54.99,
    image: "/image/boucle2.PNG",
    category: "bijoux",
  },
  {
    id: 19,
    name: "Chaîne et bracelet dorés",
    description: "Parure raffinée en métal doré, idéale pour les grandes occasions.",
    price: 99.99,
    image: "/image/chaine_bracelet.PNG",
    category: "bijoux",
  },
  {
    id: 20,
    name: "Ensemble diamant",
    description: "Collier et boucles assortis, un incontournable de l’élégance.",
    price: 149.99,
    image: "/image/ensemble_diamant.PNG",
    category: "bijoux",
  },
    {
    id: 21,
    name: "Stylos Bic",
    description: "Paquet de stylos Bic bleus, écriture fluide et durable.",
    price: 5.99,
    image: "/image/bic.PNG",
    category: "école",
  },
  {
    id: 22,
    name: "Chemise en jean",
    description: "Blouson tendance en jean, confortable et décontracté.",
    price: 49.99,
    image: "/image/blouson.PNG",
    category: "vêtement",
  },
  {
    id: 23,
    name: "Cahier petit format",
    description: "Cahier de notes avec couverture rigide et 200 pages lignées.",
    price: 3.99,
    image: "/image/cahier.PNG",
    category: "école",
  },
  {
    id: 24,
    name: "Cahier grands carreaux",
    description: "Idéal pour les élèves, 96 pages grands carreaux.",
    price: 4.49,
    image: "/image/cahier_grand_carreaux.PNG",
    category: "école",
  },
  {
    id: 25,
    name: "Boîte de crayons Crayola",
    description: "24 crayons de couleur pour les projets artistiques.",
    price: 7.99,
    image: "/image/crayola.PNG",
    category: "école",
  },
  {
    id: 26,
    name: "Ensemble sportif femme",
    description: "Tenue de sport confortable pour l’entraînement ou la détente.",
    price: 39.99,
    image: "/image/ensemble.PNG",
    category: "vêtement",
  },
  {
    id: 27,
    name: "Pack de maquillage complet",
    description: "Trousse complète contenant rouges à lèvres, fards et pinceaux.",
    price: 89.99,
    image: "/image/pack_makup.PNG",
    category: "maquillage",
  },
  {
    id: 28,
    name: "Poudre bronzante",
    description: "Texture légère et effet naturel pour un teint lumineux.",
    price: 24.99,
    image: "/image/poudre.PNG",
    category: "maquillage",
  },
  {
    id: 29,
    name: "Range documents A4",
    description: "Classeur rigide pour ranger et organiser vos papiers.",
    price: 9.99,
    image: "/image/range_doc.PNG",
    category: "école",
  },
  {
    id: 30,
    name: "Règle fluo 30 cm",
    description: "Règle transparente avec graduations précises et couleurs assorties.",
    price: 2.49,
    image: "/image/regle.PNG",
    category: "école",
  },
  {
    id: 31,
    name: "Rouge à lèvres classique",
    description: "Rouge intense longue tenue pour un look sophistiqué.",
    price: 19.99,
    image: "/image/rouge a levre.PNG",
    category: "maquillage",
  },
  {
    id: 32,
    name: "Feutres Sharpie",
    description: "Marqueurs permanents assortis, couleurs vives et durables.",
    price: 12.99,
    image: "/image/sharpie.PNG",
    category: "école",
  },
  {
    id: 33,
    name: "T-shirt Bitcoin",
    description: "T-shirt bleu à imprimé Bitcoin, 100 % coton.",
    price: 29.99,
    image: "/image/teeshirt.PNG",
    category: "vêtement",
  },

  {
  id: 34,
  name: "Jean classique bleu",
  description: "Jean coupe droite en denim, confortable et indémodable.",
  price: 59.99,
  image: "/image/jeans.PNG",
  category: "vêtement",
},
{
  id: 35,
  name: "Veste matelassée rose",
  description: "Veste légère et élégante, parfaite pour la mi-saison.",
  price: 79.99,
  image: "/image/veste.PNG",
  category: "vêtement",
},


];

export default products;
