# Generated by Django 5.2.6 on 2025-11-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="lien",
            field=models.ImageField(upload_to=""),
        ),
    ]
