# Generated by Django 5.2.6 on 2025-11-07 21:38

import minio_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0002_alter_image_lien"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="lien",
            field=models.ImageField(
                storage=minio_storage.storage.MinioMediaStorage, upload_to="media/"
            ),
        ),
    ]
